// Code generated by Slice Machine. DO NOT EDIT.

import HeroSection from './HeroSection/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	hero_section: HeroSection,
	rich_text: RichText
};
